Added functionality to return promotion via status
CSCI-GA-2820-FA22-003/promotions pull request #52
Opened 2022-11-13 19:47 UTC by Awesalot

- Ability to fetch active promotions using status
- 95% coverage
- 10.0 Pylint score

2022-11-13 23:52 UTC, Aman-Chopra commented on service/models.py
> +    def find_by_status(cls, status):
def find_by_status(cls, available: bool = True) -> list:

2022-11-13 23:55 UTC, Aman-Chopra commented on service/models.py
> +        """Returns all Promotions with the given status
"""Returns all Promotions by their status
:param status: True for promotions that are active
:type available: bool
:return: a collection of Promotions that are active or inactive based on given status
:rtype: list
"""

2022-11-13 23:55 UTC, Aman-Chopra commented on service/routes.py
> +
promotions = []

2022-11-13 23:56 UTC, Aman-Chopra requested changes
Suggested some additions, please add them and raise another pull request

2022-11-13 23:57 UTC, Aman-Chopra commented on service/routes.py
> +
Add promotions = [] before status_type

2022-11-14 02:16 UTC, Awesalot commented
Deleted find_by_name as the functionality is currently not required

2022-11-14 02:16 UTC, Aman-Chopra approved these changes
LGTM!

2022-11-14 02:32 UTC, Black-Caesaris approved these changes
LGTM!

2022-11-14 02:34 UTC, merged